import { useMemo, useState } from "react";
import { ChevronDown, Info, Lightbulb, ShieldCheck, TrendingDown, TrendingUp } from "lucide-react";
import {
  BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Tooltip, Cell, ReferenceLine,
} from "recharts";
import { explainHealthScore, factorColor, type FactorContribution } from "@/lib/preventai/explain";
import type { AssessmentReport } from "@/lib/preventai/types";

export function ExplainPanel({ report }: { report: AssessmentReport }) {
  const exp = useMemo(() => explainHealthScore(report), [report]);
  const [open, setOpen] = useState<string | null>(exp.topNegatives[0]?.key ?? exp.factors[0].key);

  const chartData = exp.factors.map((f) => ({
    name: f.key,
    contributed: f.weighted,
    lost: f.lost,
    max: f.maxWeighted,
    fill: factorColor(f.impact),
  }));

  return (
    <section className="mt-6 glass rounded-3xl p-6 lg:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-[color:var(--brand)]" />
            <h3 className="font-display text-2xl font-semibold">Why this score?</h3>
            <span className="rounded-full border border-border/70 bg-background/40 px-2 py-0.5 text-[10px] uppercase tracking-widest text-muted-foreground">
              Explainable AI
            </span>
          </div>
          <p className="mt-2 max-w-2xl text-sm text-muted-foreground">{exp.summary}</p>
        </div>
        <div className="flex gap-3">
          <Pill icon={ShieldCheck} label="Baseline" value="100" tone="muted" />
          <Pill icon={TrendingDown} label="Lost" value={`−${exp.totalLost}`} tone="danger" />
          <Pill icon={TrendingUp} label="Your score" value={`${exp.finalScore}`} tone="brand" />
        </div>
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_1fr]">
        {/* Contribution chart */}
        <div className="rounded-2xl border border-border/70 bg-background/40 p-4">
          <div className="flex items-center justify-between">
            <div className="text-sm font-medium">Per-factor contribution</div>
            <div className="text-xs text-muted-foreground">points toward final score</div>
          </div>
          <div className="mt-3 h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} layout="vertical" margin={{ left: 8, right: 16, top: 8, bottom: 8 }}>
                <XAxis type="number" domain={[0, 30]} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis type="category" dataKey="name" tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} width={70} />
                <Tooltip
                  cursor={{ fill: "color-mix(in oklab, var(--foreground) 6%, transparent)" }}
                  contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 10, fontSize: 12 }}
                  formatter={(v: number, k) => [`${v} pts`, k === "contributed" ? "Earned" : "Lost"]}
                />
                <ReferenceLine x={20} stroke="var(--border)" strokeDasharray="3 3" />
                <Bar dataKey="contributed" stackId="s" radius={[6, 0, 0, 6]}>
                  {chartData.map((d, i) => <Cell key={i} fill={d.fill} />)}
                </Bar>
                <Bar dataKey="lost" stackId="s" fill="color-mix(in oklab, var(--danger) 25%, transparent)" radius={[0, 6, 6, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <Legend />
        </div>

        {/* Drivers accordion */}
        <div className="space-y-2">
          {exp.factors.map((f) => (
            <DriverRow key={f.key} factor={f} open={open === f.key} onToggle={() => setOpen(open === f.key ? null : f.key)} />
          ))}
        </div>
      </div>

      <div className="mt-6 flex items-start gap-3 rounded-2xl border border-border/70 bg-background/40 p-4 text-xs text-muted-foreground">
        <Info className="mt-0.5 h-4 w-4 shrink-0 text-[color:var(--brand)]" />
        <p>
          Explanations are generated by attributing each factor's contribution to the weighted Health Score
          (Heart 30% · Diabetes 20% · Body 20% · Sleep 15% · Stress 15%) and surfacing the specific inputs
          that drove each sub-risk. This is informational, not a medical diagnosis.
        </p>
      </div>
    </section>
  );
}

function DriverRow({ factor, open, onToggle }: { factor: FactorContribution; open: boolean; onToggle: () => void }) {
  const color = factorColor(factor.impact);
  return (
    <div className="rounded-xl border border-border/70 bg-background/40">
      <button onClick={onToggle} className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left">
        <div className="flex items-center gap-3 min-w-0">
          <span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: color }} />
          <div className="min-w-0">
            <div className="truncate text-sm font-medium">{factor.label}</div>
            <div className="text-xs text-muted-foreground">
              {factor.level} · weight {Math.round(factor.weight * 100)}% ·{" "}
              <span style={{ color }}>{factor.weighted} / {factor.maxWeighted} pts</span>
            </div>
          </div>
        </div>
        <ChevronDown className={`h-4 w-4 text-muted-foreground transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="border-t border-border/70 px-4 py-3">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">Key drivers</div>
          <ul className="mt-2 space-y-1.5">
            {factor.drivers.map((d) => (
              <li key={d} className="flex gap-2 text-sm">
                <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full" style={{ background: color }} />
                {d}
              </li>
            ))}
          </ul>
          <div className="mt-3 rounded-lg bg-[color:color-mix(in_oklab,var(--brand)_10%,transparent)] px-3 py-2 text-xs">
            <span className="font-medium text-[color:var(--brand)]">Next step: </span>
            <span className="text-foreground/90">{factor.advice}</span>
          </div>
        </div>
      )}
    </div>
  );
}

function Pill({ icon: Icon, label, value, tone }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string; tone: "brand" | "danger" | "muted" }) {
  const color = tone === "brand" ? "var(--brand)" : tone === "danger" ? "var(--danger)" : "var(--muted-foreground)";
  return (
    <div className="rounded-xl border border-border/70 bg-background/40 px-3 py-2">
      <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-widest text-muted-foreground">
        <Icon className="h-3 w-3" /> {label}
      </div>
      <div className="font-display text-lg font-semibold tabular-nums" style={{ color }}>{value}</div>
    </div>
  );
}

function Legend() {
  return (
    <div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
      <span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: "var(--success)" }} /> Boosting</span>
      <span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: "var(--brand)" }} /> Neutral</span>
      <span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: "var(--danger)" }} /> Dragging</span>
      <span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: "color-mix(in oklab, var(--danger) 25%, transparent)" }} /> Points lost</span>
    </div>
  );
}
